# zshenv
# this file should contain commands to set the command search path,
# plus other important environment variables; it should not contain
# commands that produce output or assume the shell is attached to
# a tty

export PATH="{{ path }}"

{{ zshenv | replace('\\n', '\n') }}